### PR TITLE
Add diamond

### PR DESCRIPTION
**Pull request by Hackzzila**
I was not sure where to put it, so I put under "GUIs, Editors and Plugins" because part of it is a plugin.

### CODE REVIEW

**Comment by LucasBassetti** [comment]
Hi,

The [link](https://diamond.js.org/) is not working here. Can you check it please?

Thanks for contributing!

**Comment by Hackzzila** [comment]
It works for me 😕
4e7cbb

**Comment by LucasBassetti** [comment]
I got this problem

image

**Comment by LucasBassetti** [comment]
I try again and it's working now. Thanks!

**Pull request merged**
